Спринт № 13. Ревью № 1.
FedoRScorpioN/java-shareit pull request #1
Opened 2023-01-23 04:37 UTC by FedoRScorpioN

2023-01-23 07:38 UTC, LexLippi requested changes
Привет!

Неплохая работа!
Есть несколько вопросов и замечаний по поводу твоей реализации.

Желаю удачи!!!

2023-01-23 07:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/Create.java
> +public interface Create {
Не очень понятно зачем нужен такой интерфейс.

1. Он пустой
2. У него не очень информативное название
3. Он лежит в корне проекта, а не в специализированном пакете

Эти 3 свойства очень смущают

2023-01-23 07:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/Update.java
> +public interface Update {
Аналогичные замечания, как и к интерфейсу `Create`

2023-01-23 07:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/Status.java
> +public enum Status {
Лучше в названии указывать какому объекту принадлежит этот статус `BookingStatus`, в данном случае

2023-01-23 07:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public final ItemService itemService;
А почему модификатор `public`?

2023-01-23 07:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final String headerUserId = "X-Sharer-User-Id";
Можно это поле сделать статическим

2023-01-23 07:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryInMemory.java
> +    public final UserService userService;
Почему модификатор `public`?

2023-01-23 07:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryInMemory.java
> +        return repoItem;
А само обновление состояния объекта в хранилище, где?

2023-01-23 07:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryInMemory.java
> +        items.remove(id);
В случае если у нас не может быть значения `null`, как в случае возвращаемого значения, то лучше использовать примитивный тип, а не объектный

2023-01-23 07:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public final UserService userService;
Почему модификатор такой?

2023-01-23 07:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserRepositoryInMemory.java
> +            emailIsAvailable(user);
Это не совсем верная проверка, как мне кажется.
В таком случае мы не можем прислать данные на обновление пользователя с не изменившейся почте.

Мне кажется такое поведение странным, поскольку тогда на стороне вызывющего кода придётся запоминать, какая почта была у пользователя, что не всегда удобно

2023-01-23 07:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserRepositoryInMemory.java
> +        return repoUser;
Также не вижу обновления данных в хранилище

2023-01-23 07:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserRepositoryInMemory.java
> +        return true;
Про объектный тип уже писал выше

2023-01-23 08:21 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/Create.java
> +public interface Create {
Необходим для разделения функциональности между классами User и Item.
Исправил.

2023-01-23 08:21 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/Update.java
> +public interface Update {
Необходим для разделения функциональности между классами User и Item.
Исправил.

2023-01-23 08:23 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/booking/Status.java
> +public enum Status {
Исправил.

2023-01-23 08:27 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public final ItemService itemService;
Исправил.

2023-01-23 08:29 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final String headerUserId = "X-Sharer-User-Id";
Подправил.

2023-01-23 08:30 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryInMemory.java
> +    public final UserService userService;
Исправил.

2023-01-23 08:37 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryInMemory.java
> +        return repoItem;
Не могу уловить суть вопроса. По условиям задачи мы меняем только 3 значения:
_"Редактирование вещи. Эндпойнт PATCH /items/{itemId}. Изменить можно название, описание и статус доступа к аренде. Редактировать вещь может только её владелец."_

2023-01-23 08:40 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryInMemory.java
> +        items.remove(id);
Изменил.

2023-01-23 08:41 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public final UserService userService;
Исправил.

2023-01-23 08:58 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/user/UserRepositoryInMemory.java
> +            emailIsAvailable(user);
Один из тестов Постман требует проверять почту на null.

2023-01-23 09:22 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/user/UserRepositoryInMemory.java
> +        return true;
Изменил.

2023-01-23 09:26 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryInMemory.java
> +        return repoItem;
Добавил.

2023-01-23 09:26 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/user/UserRepositoryInMemory.java
> +        return repoUser;
Добавил.

2023-01-23 09:28 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/user/UserRepositoryInMemory.java
> +            emailIsAvailable(user);
Но хотелось бы вникнуть в это и сделать адекватную проверку. Скажи, как лучше написать или где про это можно почитать (может примеры какие-то). Я понимаю, что по логике надо предоставить возможность изменять данные, при этом не менять почту.

2023-01-24 07:52 UTC, LexLippi reviewed
Привет!

Ответил на твой вопрос. Если есть желание можно исправить и перезаслать работу. Если нет перещашли ее снова, я её приму.

Желаю удачи!

2023-01-24 07:52 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserRepositoryInMemory.java
> +            emailIsAvailable(user);
Проверять почту на `null` это ок. 
Я имею в виду, что при обновлении пользователя стоит проверять занята ли почта тогда и только тогда, когда почта в `repoUser` и `user` не совпадает.

Поскольку иначе, если в объекте для обновления указать ту же самую почту, то мы получим статус `409 CONFLICT`, что не очень хорошо, как мне кажется

2023-01-24 08:05 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/user/UserRepositoryInMemory.java
> +            emailIsAvailable(user);
Исправил. Даже тесты Постмана прошёл. Но потом понял, что так тоже неправильно будет. Откатился. К сдаче следующего спринта попробую это реализовать.

2023-01-24 08:21 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserRepositoryInMemory.java
> +            emailIsAvailable(user);
Хорошо

2023-01-24 08:22 UTC, LexLippi approved these changes

2023-02-27 12:47 UTC, merged