Спринт № 14. Ревью № 1.
FedoRScorpioN/java-shareit pull request #2
Opened 2023-02-27 23:09 UTC by FedoRScorpioN

2023-02-28 07:41 UTC, LexLippi commented
Привет!

Прежде, чем я приступлю проверке необходимо исправить тесты POSTMAN. С этим тебе может помочь наставник.

Желаю удачи!

2023-03-01 06:38 UTC, LexLippi requested changes
Привет!

Неплохая работа, но есть некоторое количество замечаний, которые надо исправить!

Желаю удачи!

2023-03-01 06:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private final String headerUserId = "X-Sharer-User-Id";
Константу лучше делать статическим полем

2023-03-01 06:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                            @RequestParam() Boolean approved) {
можно без скобок обойтись

2023-03-01 06:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    }
если используешь `defaultValue`, то можно не указывать `required = false`

2023-03-01 06:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +            "OR UPPER(i.description) LIKE UPPER(CONCAT('%', ?1, '%'))) " +
для регистронезависимого сравнения строк можно использовать оператор `ILIKE`

2023-03-01 06:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +            "AND i.available = true")
`CLAUSE` с булевским полем может выглядеть просто, как:

```sql
AND i.available
```

2023-03-01 06:38 UTC, LexLippi commented on src/main/resources/application.properties
>  #---
такие комментарии лучше не оставлять

2023-03-01 06:38 UTC, LexLippi commented on src/main/resources/schema.sql
> +
Это странный способ заполнить схему.
Ты сначала удаляешь все таблицы, а потом пишешь `CREATE TABLE IF NOT EXISTS`. Ты их только что удалил, конечно они не существуют. 

/Поэтому надо либо отказаться от `drop table`, либо от `not exists`.

2023-03-01 06:38 UTC, LexLippi commented on src/main/resources/schema.sql
> +    AVAILABLE boolean,
Может быть `null`?

2023-03-01 06:38 UTC, LexLippi commented on src/main/resources/schema.sql
> +    TEXT TEXT,
лучше не называть колонку также, как и тип данных

2023-03-01 07:00 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private final String headerUserId = "X-Sharer-User-Id";
Понял. Исправил.

2023-03-01 07:03 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                            @RequestParam() Boolean approved) {
Подправил

2023-03-01 07:05 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    }
Исправил.

2023-03-01 07:58 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +            "OR UPPER(i.description) LIKE UPPER(CONCAT('%', ?1, '%'))) " +
Этот оператор есть только в PostgreSQL, а мы сдаём проект на H2. Читал в чатах, что ребята обсуждали это с куратором, он сказал делать на H2, так как тесты Postman под H2 сделаны.

2023-03-01 08:00 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +            "AND i.available = true")
В таком случае приложение не хочет компилироваться и запускаться...

2023-03-01 08:01 UTC, FedoRScorpioN commented on src/main/resources/application.properties
>  #---
Понял. Пытался сделать на PostgreSQL, но как уже писал вышел потом прочитал, что надо делать на H2.

2023-03-01 08:04 UTC, FedoRScorpioN commented on src/main/resources/schema.sql
> +
Исправил.

2023-03-01 08:18 UTC, FedoRScorpioN commented on src/main/resources/schema.sql
> +    AVAILABLE boolean,
Если честно не понял вопроса. Если про NAME, то конечно не может быть, поэтому и NOT NULL.
Если про DESCRIPTION, то на мой взгляд описание вещи вполне может и отсутствовать. Хотя его тоже можно сделать NOT NULL. Пусть будущие пользователи не ленятся и тоже его заполняют) 

Исправил.

2023-03-01 08:22 UTC, FedoRScorpioN commented on src/main/resources/schema.sql
> +    TEXT TEXT,
Понял. Исправил.

2023-03-02 06:46 UTC, LexLippi requested changes
Привет, отличная работа.

Остался один маленький вопросик, ответь на него или исправь, и перезасылай работу, я ее приму.

Желаю удачи!!!

2023-03-02 06:46 UTC, LexLippi commented on src/main/resources/schema.sql
> +    AVAILABLE boolean,
Я имел в виду именно колонку `AVAILABLE`, поэтому на этой строчке оставил комментарий.

В `SQL` тип `boolean` может хранить три значения: `TRUE`, `FALSE`, `NULL`. Поэтому я и уточнил хочешь ли ты, чтобы это поле могло содержать значения `NULL`, если нет, то лучше добавить ограничение на уровне `SQL`, дописав, что эта колонка `NOT NULL`

2023-03-02 08:41 UTC, FedoRScorpioN commented
Привет. Согласен. Упустил момент, что значение может быть NULL. Поэтому нужно ограничение. Вещь может быть либо забронирована, либо свободна, иное может запутать пользователей.

2023-03-03 06:56 UTC, LexLippi approved these changes
Привет, отличная работа!

Желаю удачи в следующих спринтах!!!

2023-03-03 07:05 UTC, merged