Спринт № 15. Ревью № 1.
FedoRScorpioN/java-shareit pull request #3
Opened 2023-03-04 09:21 UTC by FedoRScorpioN

2023-03-05 09:17 UTC, LexLippi requested changes
Привет!

Отличная работа!

Есть пара небольших замечаний, которые надо исправить!

Желаю удачи!!!

2023-03-05 09:17 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestParam(defaultValue = "ALL", required = false) String state,
Если указываем `defaultValue`, то `required` необязательно к использованию

2023-03-05 09:17 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                    @RequestParam(defaultValue = "ALL", required = false) String state,
Аналогично про `required`

2023-03-05 09:17 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @PatchMapping("/{id}")  //Проверить
Такие комментарии не стоит оставлять

2023-03-05 09:17 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            Booking lastBooking = bookings.get(0);
Можно использовать `Stream API`

```java
bookings.stream().findFirst().map().orElse();
```

2023-03-05 09:17 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        }
Аналогично можно использовать `Stream API`

2023-03-05 09:17 UTC, LexLippi commented on src/main/resources/application.properties
> +#spring.jpa.properties.hibernate.show_sql=false
лучше полностью это удалять, мы для этого и пользуемся системой контроля версий, чтобы такие изменения в случае чего можно было вернуть из предыдущих коммитов

2023-03-05 09:17 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/user/UserBranchesTest.java
> +    private void checkUserDto(UserDto userDto, UserDto userDtoFromController) {
модификаторы доступа в тестах стараются не использовать

2023-03-05 09:55 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestParam(defaultValue = "ALL", required = false) String state,
Убрал.

2023-03-05 09:55 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                    @RequestParam(defaultValue = "ALL", required = false) String state,
Убрал

2023-03-05 09:58 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @PatchMapping("/{id}")  //Проверить
Исправил

2023-03-05 10:14 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            Booking lastBooking = bookings.get(0);
Исправил.

2023-03-05 10:15 UTC, FedoRScorpioN commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        }
Исправил

2023-03-05 10:16 UTC, FedoRScorpioN commented on src/main/resources/application.properties
> +#spring.jpa.properties.hibernate.show_sql=false
Понял. Убрал.

2023-03-05 10:17 UTC, FedoRScorpioN commented on src/test/java/ru/practicum/shareit/user/UserBranchesTest.java
> +    private void checkUserDto(UserDto userDto, UserDto userDtoFromController) {
Исправил.

2023-03-06 08:22 UTC, LexLippi approved these changes
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!!!

2023-03-06 08:39 UTC, merged