Спринт № 16. Ревью № 1. Tests Postman.
FedoRScorpioN/java-shareit pull request #4
Opened 2023-03-07 10:18 UTC by FedoRScorpioN

2023-03-08 17:57 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть несколько небольших замечаний!

Желаю удачи!!!

2023-03-08 17:57 UTC, LexLippi commented on checkstyle.xml
> +<!--		</module>-->
А это зачем?

2023-03-08 17:57 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingRequestDto.java
> +package ru.practicum.shareit.booking;
А почему вытащил из пакета `dto`?

2023-03-08 17:57 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.error("400 {}", exception.getMessage(), exception);
Что здесь символизирует 400?
Если это код ответа сервиса, то это неправда: `INTERNAL_SERVER_ERROR` - 500

2023-03-08 17:57 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/item/ItemClient.java
> +public class ItemClient extends BaseClient {
Этот класс лучше сделать `final`, чтобы продемонстрировать, что у него не планируется заводить наследников.

Чтобы никто не мог переопределить его функционал, буз изменения этого класса, в таком случае разработчик точно подумает о необходимости этого решения

2023-03-08 17:57 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public static final String PAGE_DEFAULT_SIZE = "10";
А эти константы используются в этом файле?
А то я этого не вижу. 

Мне кажется странным хранить константы в контроллере, если они в нем не используются

2023-03-08 17:57 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/user/UserDto.java
> +package ru.practicum.shareit.user;
А почему убрал из пакета `dto`?

2023-03-08 17:57 UTC, LexLippi commented on server/src/main/java/ru/practicum/shareit/booking/State.java
> +}
Кажется, тут смешаны два перечисления. `State` - это `WAITING`, `REJECT`
А `ALL, CURRENT, PAST, FUTURE` - это не состояние бронирования.

Кстати, если это относится к бронированию, то, кмк, уместнее использовать `BookingState`

2023-03-08 17:57 UTC, LexLippi commented on server/src/main/java/ru/practicum/shareit/item/ItemController.java
> +import ru.practicum.shareit.user.UserController;
Лучше такими импортами не пользоваться, стоит считать, что два твоих сервиса должы быть полностью независимы.

На практике, их код может лежать в разных репозиториях (а чаще всего так и бывает), так что лучше не использовать такие импорты

2023-03-08 17:57 UTC, LexLippi commented on server/src/main/resources/schema.sql
> +drop table IF EXISTS users cascade;
Мне вот это не очень нравится.
Представь у тебя промышленное приложение, которое работает несколько лет, в нем есть какие-то данные, и ты при каждом обновлении хочешь это все стирать?

Кажется, что нет. Стоит посмотреть в сторону `CREATE TABLE IF NOT EXISTS`, это очень похоже на то, что ты делаешь, за исключением удаления данных

2023-03-08 21:22 UTC, FedoRScorpioN commented on checkstyle.xml
> +<!--		</module>-->
Поправил.

Не проверил этот файл. Он был в репозитарии из ТЗ.
https://github.com/yandex-praktikum/java-shareit/blob/add-docker/checkstyle.xml

2023-03-08 21:24 UTC, FedoRScorpioN commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingRequestDto.java
> +package ru.practicum.shareit.booking;
Подправил.

2023-03-08 21:24 UTC, FedoRScorpioN commented on gateway/src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.error("400 {}", exception.getMessage(), exception);
Спасибо. Подправил.

2023-03-08 21:25 UTC, FedoRScorpioN commented on gateway/src/main/java/ru/practicum/shareit/item/ItemClient.java
> +public class ItemClient extends BaseClient {
Понял. Исправил.

2023-03-08 21:40 UTC, FedoRScorpioN commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public static final String PAGE_DEFAULT_SIZE = "10";
Сделал рефакторинг.

2023-03-08 21:42 UTC, FedoRScorpioN commented on gateway/src/main/java/ru/practicum/shareit/user/UserDto.java
> +package ru.practicum.shareit.user;
Аналогично Booking. Исправил.

2023-03-08 21:54 UTC, FedoRScorpioN commented on server/src/main/java/ru/practicum/shareit/booking/State.java
> +}
Это не статусы вещи, это про выборку бронирований пользователя. 
Из финального ТЗ Спринта № 14:
_"Получение списка всех бронирований текущего пользователя. Эндпоинт — GET /bookings?state={state}. Параметр state необязательный и по умолчанию равен ALL (англ. «все»). Также он может принимать значения CURRENT (англ. «текущие»), **PAST** (англ. «завершённые»), FUTURE (англ. «будущие»), WAITING (англ. «ожидающие подтверждения»), REJECTED (англ. «отклонённые»). Бронирования должны возвращаться отсортированными по дате от более новых к более старым."_

Наименование подправил (попробую протестировать, у меня вроде из-за него тесты падали, поэтому и вернул обратно).

2023-03-08 22:04 UTC, FedoRScorpioN commented on server/src/main/java/ru/practicum/shareit/item/ItemController.java
> +import ru.practicum.shareit.user.UserController;
Исправил.

2023-03-08 22:12 UTC, FedoRScorpioN commented on server/src/main/resources/schema.sql
> +drop table IF EXISTS users cascade;
Локальные тесты не проходят (падает 64 штуки из 203), поэтому переделал. А вообще я согласен, что терять данные это плохо... Вернул обратно, попробую пройти тесты на ГитеХабе.

2023-03-09 05:39 UTC, LexLippi commented on server/src/main/java/ru/practicum/shareit/booking/State.java
> +}
ага, ок, понял

2023-03-09 06:19 UTC, LexLippi commented on server/src/main/resources/schema.sql
> +drop table IF EXISTS users cascade;
Да, скорее всего в двух вещах:

1. Для корректного прохождения тестов необходима чистая неинициализированная БД
2. Поэтому, когда ты запускаешь локально, то данные у тебя в БД остаются. А когда ты запускаешь это все дело в докер-контейнере, то система каждый раз реинициализируется (для тестового окружения, это ок, главное, чтобы в проде так не работало :)), поэтому пункт 1 выполняется

как-то так

2023-03-09 06:20 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи с дипломным проектом!!!

2023-03-09 06:26 UTC, FedoRScorpioN commented on server/src/main/resources/schema.sql
> +drop table IF EXISTS users cascade;
Спасибо)))

2023-03-09 06:28 UTC, merged